apiVersion: apps/v1
kind: Deployment
metadata:
  name: final
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final
  template:
    metadata:
      labels:
        app: final
    spec:
      containers:
      - name: final
        image: resmasre/final:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: NodePort
  selector:
    app: final
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30036
